### ISSUE TITLE
Null pointer exceptions.

### ISSUE THREAD

**Issue by yussidivnall** [retsamknaps/aktie#3]
Got these where first running. IRC told me to paste this here. Still hasn't got an identity or communities (after about 30 mins). got 3 connections showing.

CALLING UPDATE!
CALLING UPDATE!
CALLING UPDATE!
STOPPING!
Exception in thread "Thread-82" java.lang.NullPointerException
	at aktie.i2p.I2PConnection.close(I2PConnection.java:66)
	at aktie.net.ConnectionThread.stop(ConnectionThread.java:177)
	at aktie.net.ConnectionThread.run(ConnectionThread.java:1159)
	at java.lang.Thread.run(Thread.java:745)
STOPPING!
Exception in thread "Thread-83" java.lang.NullPointerException
	at aktie.i2p.I2PConnection.close(I2PConnection.java:66)
	at aktie.net.ConnectionThread.stop(ConnectionThread.java:177)
	at aktie.net.ConnectionThread.run(ConnectionThread.java:1159)
	at java.lang.Thread.run(Thread.java:745)
STOPPING!
Exception in thread "Thread-84" java.lang.NullPointerException
	at aktie.i2p.I2PConnection.close(I2PConnection.java:66)
	at aktie.net.ConnectionThread.stop(ConnectionThread.java:177)
	at aktie.net.ConnectionThread.run(ConnectionThread.java:1159)
	at java.lang.Thread.run(Thread.java:745)
STOPPING!
Exception in thread "Thread-85" java.lang.NullPointerException
	at aktie.i2p.I2PConnection.close(I2PConnection.java:66)
	at aktie.net.ConnectionThread.stop(ConnectionThread.java:177)
	at aktie.net.ConnectionThread.run(ConnectionThread.java:1159)
	at java.lang.Thread.run(Thread.java:745)

**Comment by retsamknaps** [comment]
Do you already have a router running?

**Comment by retsamknaps** [comment]
Not closed.  Will review.

**Comment by yussidivnall** [comment]
I did have the i2p router running, yes.

**Comment by retsamknaps** [comment]
fixed
