### ISSUE TITLE
Aktie will not run on Trisquel 7 Gnu-Linux

### ISSUE THREAD

**Issue by im-grey** [retsamknaps/Aktie#44]
```

me@pc:~$ java -jar aktie_0.4.13.jar 
SYS: Linux
java.io.FileNotFoundException: aktie.jar (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at aktie.gui.Wrapper.unZipIt(Wrapper.java:462)
    at aktie.gui.Wrapper.Main(Wrapper.java:98)
    at aktie.gui.Wrapper.main(Wrapper.java:50)
Upgrade list: 0
LIST LIBS: aktie_run_dir/lib
Error: Could not find or load main class aktie.gui.SWTApp
EXITING..
RC: 1
me@pc:~$ 
```

**Comment by retsamknaps** [comment]
The jar file is always expected to be aktie.jar.  Rename aktie_0.4.13.jar to aktie.jar and try again.

**Comment by retsamknaps** [comment]
Thank you for pointing this out.  We need to make sure we upload our release files as aktie.jar until we fix this.

**Comment by retsamknaps** [comment]
Should be fixed in the next release.
