### ISSUE TITLE
Aktie 0.4.15 wont start in folder with spaces

### ISSUE THREAD

**Issue by slothbag** [retsamknaps/Aktie#45]
I had the same issue for the last few builds too.. This is the error..

When I run it in a folder with no spaces it works

```
SYS: Windows 8.1
java.io.FileNotFoundException: C:\name%20with%20spaces\aktie_0.4.15.jar (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at aktie.gui.Wrapper.unZipIt(Wrapper.java:466)
        at aktie.gui.Wrapper.Main(Wrapper.java:98)
        at aktie.gui.Wrapper.main(Wrapper.java:50)
Upgrade list: 0
LIST LIBS: aktie_run_dir\lib
Error: Could not find or load main class aktie_run_dir\aktie_node
EXITING..
RC: 1
```

**Comment by retsamknaps** [comment]
Ok.  Will fix in next release.
