### ISSUE TITLE
App crashes on OSX

### ISSUE THREAD

**Issue by slothbag** [retsamknaps/Aktie#50]
App crashes after a few seconds of clicking around the UI.

```
java.lang.NullPointerException
    at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
    at org.eclipse.swt.graphics.GC.cocoa_new(Unknown Source)
    at org.eclipse.swt.widgets.Table.sendMeasureItem(Unknown Source)
    at org.eclipse.swt.widgets.Table.cellSize(Unknown Source)
    at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper_stret(Native Method)
    at org.eclipse.swt.widgets.Widget.expansionFrameWithFrame_inView(Unknown Source)
    at org.eclipse.swt.widgets.Table.expansionFrameWithFrame_inView(Unknown Source)
    at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
    at org.eclipse.swt.internal.cocoa.NSRunLoop.runMode(Unknown Source)
    at org.eclipse.swt.widgets.Display.sleep(Unknown Source)
    at aktie.gui.SWTApp.open(SWTApp.java:2095)
    at aktie.gui.SWTApp.main(SWTApp.java:1534)
```

**Comment by retsamknaps** [comment]
I couldn't duplicate this, but based on bug reports for SWT we upgraded for this.  Please download release 0.5.1 to see if it helps.
